// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFOAEPInHNIs-chm36HRrHppBIHgbuwkE',
    appId: '1:487805485135:web:6458d79d41212f22fdea3a',
    messagingSenderId: '487805485135',
    projectId: 'drinks-app-53133',
    authDomain: 'drinks-app-53133.firebaseapp.com',
    storageBucket: 'drinks-app-53133.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu__ViaPKUUe3Ez3JECLguEQz1OSB1iXw',
    appId: '1:487805485135:android:242a323e2f6a5232fdea3a',
    messagingSenderId: '487805485135',
    projectId: 'drinks-app-53133',
    storageBucket: 'drinks-app-53133.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGq-aBEFj0n3FSvGttlb20a8UDa2-Eb-o',
    appId: '1:487805485135:ios:0e56a29c1cc4a65afdea3a',
    messagingSenderId: '487805485135',
    projectId: 'drinks-app-53133',
    storageBucket: 'drinks-app-53133.appspot.com',
    iosBundleId: 'com.example.drinksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGq-aBEFj0n3FSvGttlb20a8UDa2-Eb-o',
    appId: '1:487805485135:ios:ef734b66a3acc458fdea3a',
    messagingSenderId: '487805485135',
    projectId: 'drinks-app-53133',
    storageBucket: 'drinks-app-53133.appspot.com',
    iosBundleId: 'com.example.drinksApp.RunnerTests',
  );
}
